### ISSUE TITLE
Unable to play output files

### ISSUE THREAD

**Issue by ghost** [avibrazil/un-istore#1]
foobar2000 is giving me this error when trying to play the output files:

```
Unable to open item for playback (Unsupported format or corrupted file (invalid box/atom header))
```

I'm running this in Git Bash on Windows, in case that changes anything – I don't have Linux installed right now. No errors output by the script, though.

**Comment by avibrazil** [comment]
Please upload the original and modified music files somewhere and provide the URL so I can download them and compare.

I never tested it on Windows. You need perl to use un-istore. You'd better have it running on a Linux VM or container.

**Comment by avibrazil** [comment]
Closing due to lack of response. I'm having zero issues with instrumented files and can't reproduce the problem.
